#!/bin/bash

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Get validator count from environment or default to 3
VALIDATOR_COUNT=${VALIDATOR_COUNT:-3}

echo -e "${YELLOW}Creating secret for ${VALIDATOR_COUNT} validators...${NC}"

# Create k8s directory if it doesn't exist
mkdir -p "$SCRIPT_DIR/../../k8s"

# Create the secret YAML file
(
cat << EOF
# This file is auto-generated by create-node-keys-secret.sh
# DO NOT EDIT THIS FILE DIRECTLY
# Last generated: $(date)
---
apiVersion: v1
kind: Secret
metadata:
  name: geth-node-keys
  namespace: ifinchain
type: Opaque
data:
EOF

# Add nodekeys and keystores for each validator
for i in $(seq 1 $VALIDATOR_COUNT); do
    # Add nodekey
    echo "  # Node $i nodekey"
    nodekey_content=$(base64 -i "$SCRIPT_DIR/../../data/node$i/geth/nodekey")
    echo "  node${i}_nodekey: ${nodekey_content}"
    
    # Add keystore
    echo "  # Node $i keystore"
    keystore_content=$(base64 -i "$SCRIPT_DIR/../../data/node$i/keystore/"*)
    echo "  node${i}_keystore: ${keystore_content}"
done

# Add password file
echo "  # Password file"
password_content=$(base64 -i "$SCRIPT_DIR/../../data/password.txt")
echo "  password.txt: ${password_content}"

) > "$SCRIPT_DIR/../../k8s/geth-node-keys-secret.yaml"

echo -e "${GREEN}Successfully created secret configuration for ${VALIDATOR_COUNT} validators${NC}"
